# Generated by Django 4.2 on 2023-04-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authorId',
            new_name='author',
        ),
    ]
